# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.FloatField(default=-1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True)),
                ('weight', models.FloatField(default=1.0)),
                ('related_to_moments_of_congruence', models.BooleanField(default=True)),
                ('related_to_ceiling_of_clouds', models.BooleanField(default=True)),
                ('related_to_in_transition', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('composer', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('duration', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paused', models.BooleanField(default=True)),
                ('position', models.FloatField(default=-1)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Music')),
            ],
        ),
        migrations.AddField(
            model_name='bullet',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Music'),
        ),
    ]
