# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='music',
            name='order',
            field=models.FloatField(default=0),
        ),
    ]
