# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20180814_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playstatus',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.Music'),
        ),
    ]
