# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20180814_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='bullet',
            name='is_keyword',
            field=models.BooleanField(default=True),
        ),
    ]
