# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_bullet_is_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bullet',
            name='is_keyword',
        ),
        migrations.AddField(
            model_name='bullet',
            name='source',
            field=models.IntegerField(choices=[(0, 'Tablet keyword'), (1, 'Tablet Input'), (2, 'QRcode Input')], default=0),
        ),
    ]
