# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20180913_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='bullet',
            name='creator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
