# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_bullet_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='related_to_ceiling_of_clouds',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='related_to_in_transition',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='related_to_moments_of_congruence',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='weight',
        ),
        migrations.AddField(
            model_name='bullet',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='keyword',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
